# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list
    silent: true

  compose:
    cmds:
      - docker compose {{.TASK_ARGS}} {{.CLI_ARGS}}
    internal: true

  composer:
    desc: Run composer inside docker compose setup, e.g. `task {{.TASK}} -- install`
    cmds:
      - task: compose
        vars:
          TASK_ARGS: run --rm phpfpm composer {{.TASK_ARGS}}

  coding-standards:apply:
    - task: coding-standards:apply:composer
    - task: coding-standards:apply:markdown
    - task: coding-standards:apply:php
    - task: coding-standards:apply:yaml

  coding-standards:apply:composer:
    - task: compose
      vars:
        TASK_ARGS: run --rm phpfpm composer normalize

  coding-standards:apply:markdown:
    - task: compose
      vars:
        TASK_ARGS: run --rm markdownlint markdownlint '**/*.md' --fix

  coding-standards:apply:php:
    - task: compose
      vars:
        TASK_ARGS: run --rm phpfpm vendor/bin/php-cs-fixer fix

  coding-standards:apply:yaml:
    - task: compose
      vars:
        TASK_ARGS: run --rm prettier '**/*.{yml,yaml}' --write

  coding-standards:check:
    - task: coding-standards:check:composer
    - task: coding-standards:check:markdown
    - task: coding-standards:check:php
    - task: coding-standards:check:yaml

  coding-standards:check:composer:
    - task: coding-standards:apply:composer
    - task: compose
      vars:
        TASK_ARGS: run --rm phpfpm composer normalize --dry-run
    - task: compose
      vars:
        TASK_ARGS: run --rm phpfpm composer validate

  coding-standards:check:markdown:
    - task: coding-standards:apply:markdown
    - task: compose
      vars:
        TASK_ARGS: run --rm markdownlint markdownlint '**/*.md'

  coding-standards:check:php:
    - task: coding-standards:apply:php
    - task: compose
      vars:
        TASK_ARGS: run --rm phpfpm vendor/bin/php-cs-fixer fix --dry-run --diff

  coding-standards:check:yaml:
    - task: coding-standards:apply:yaml
    - task: compose
      vars:
        TASK_ARGS: run --rm prettier '**/*.{yml,yaml}' --check

  # https://mago.carthage.software/latest/en/guide/getting-started/
  mago:run:
    desc: 'Run all Mago steps (cf.
      https://mago.carthage.software/latest/en/guide/getting-started/)'
    cmds:
      - task: mago:lint
      - task: mago:format
      - task: mago:analyze

  mago:lint: &mago_command
    desc: 'Run `mago {{.TASK | replace "mago:" "" }}` inside docker compose setup'
    cmds:
      - task: compose
        vars:
          TASK_ARGS: run --rm mago {{.TASK | replace "mago:" "" }}

  mago:format: *mago_command
  mago:analyze: *mago_command

  f2-api-client:run:
    desc: 'Run bin/f2-api-client inside docker compose setup, e.g. `task {{.TASK}}
      -- searchCases ''{"q": "test", "count": 10}''`'
    cmds:
      - task: compose
        vars:
          TASK_ARGS: run --quiet --rm phpfpm php bin/f2-api-client

  f2-api-client:debug:
    desc: 'Debug bin/f2-api-client inside docker compose setup, e.g. `task {{.TASK}}
      -- searchCases ''{"q": "test", "count": 10}''`'
    cmds:
      - task: compose
        vars:
          TASK_ARGS: run --quiet --env PHP_XDEBUG_MODE=debug --rm phpfpm php
            bin/f2-api-client
